from .greedy_solver import NearestNeighbourSolver
from .greedy_solver_multi_2 import NearestNeighbourMultiSolver2
from .greedy_solver_multi_4 import NearestNeighbourMultiSolver4
from .greedy_solver_vali import NearestNeighbourSolverVali